package mock

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/shopspring/decimal"
)

// ConverterMock implements internal.converter
type ConverterMock struct {
	t minimock.Tester

	funcConvert          func(from string, to string) (dp1 *decimal.Decimal, err error)
	inspectFuncConvert   func(from string, to string)
	afterConvertCounter  uint64
	beforeConvertCounter uint64
	ConvertMock          mConverterMockConvert
}

// NewConverterMock returns a mock for internal.converter
func NewConverterMock(t minimock.Tester) *ConverterMock {
	m := &ConverterMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.ConvertMock = mConverterMockConvert{mock: m}
	m.ConvertMock.callArgs = []*ConverterMockConvertParams{}

	return m
}

type mConverterMockConvert struct {
	mock               *ConverterMock
	defaultExpectation *ConverterMockConvertExpectation
	expectations       []*ConverterMockConvertExpectation

	callArgs []*ConverterMockConvertParams
	mutex    sync.RWMutex
}

// ConverterMockConvertExpectation specifies expectation struct of the converter.Convert
type ConverterMockConvertExpectation struct {
	mock    *ConverterMock
	params  *ConverterMockConvertParams
	results *ConverterMockConvertResults
	Counter uint64
}

// ConverterMockConvertParams contains parameters of the converter.Convert
type ConverterMockConvertParams struct {
	from string
	to   string
}

// ConverterMockConvertResults contains results of the converter.Convert
type ConverterMockConvertResults struct {
	dp1 *decimal.Decimal
	err error
}

// Expect sets up expected params for converter.Convert
func (mmConvert *mConverterMockConvert) Expect(from string, to string) *mConverterMockConvert {
	if mmConvert.mock.funcConvert != nil {
		mmConvert.mock.t.Fatalf("ConverterMock.Convert mock is already set by Set")
	}

	if mmConvert.defaultExpectation == nil {
		mmConvert.defaultExpectation = &ConverterMockConvertExpectation{}
	}

	mmConvert.defaultExpectation.params = &ConverterMockConvertParams{from, to}
	for _, e := range mmConvert.expectations {
		if minimock.Equal(e.params, mmConvert.defaultExpectation.params) {
			mmConvert.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmConvert.defaultExpectation.params)
		}
	}

	return mmConvert
}

// Inspect accepts an inspector function that has same arguments as the converter.Convert
func (mmConvert *mConverterMockConvert) Inspect(f func(from string, to string)) *mConverterMockConvert {
	if mmConvert.mock.inspectFuncConvert != nil {
		mmConvert.mock.t.Fatalf("Inspect function is already set for ConverterMock.Convert")
	}

	mmConvert.mock.inspectFuncConvert = f

	return mmConvert
}

// Return sets up results that will be returned by converter.Convert
func (mmConvert *mConverterMockConvert) Return(dp1 *decimal.Decimal, err error) *ConverterMock {
	if mmConvert.mock.funcConvert != nil {
		mmConvert.mock.t.Fatalf("ConverterMock.Convert mock is already set by Set")
	}

	if mmConvert.defaultExpectation == nil {
		mmConvert.defaultExpectation = &ConverterMockConvertExpectation{mock: mmConvert.mock}
	}
	mmConvert.defaultExpectation.results = &ConverterMockConvertResults{dp1, err}
	return mmConvert.mock
}

//Set uses given function f to mock the converter.Convert method
func (mmConvert *mConverterMockConvert) Set(f func(from string, to string) (dp1 *decimal.Decimal, err error)) *ConverterMock {
	if mmConvert.defaultExpectation != nil {
		mmConvert.mock.t.Fatalf("Default expectation is already set for the converter.Convert method")
	}

	if len(mmConvert.expectations) > 0 {
		mmConvert.mock.t.Fatalf("Some expectations are already set for the converter.Convert method")
	}

	mmConvert.mock.funcConvert = f
	return mmConvert.mock
}

// When sets expectation for the converter.Convert which will trigger the result defined by the following
// Then helper
func (mmConvert *mConverterMockConvert) When(from string, to string) *ConverterMockConvertExpectation {
	if mmConvert.mock.funcConvert != nil {
		mmConvert.mock.t.Fatalf("ConverterMock.Convert mock is already set by Set")
	}

	expectation := &ConverterMockConvertExpectation{
		mock:   mmConvert.mock,
		params: &ConverterMockConvertParams{from, to},
	}
	mmConvert.expectations = append(mmConvert.expectations, expectation)
	return expectation
}

// Then sets up converter.Convert return parameters for the expectation previously defined by the When method
func (e *ConverterMockConvertExpectation) Then(dp1 *decimal.Decimal, err error) *ConverterMock {
	e.results = &ConverterMockConvertResults{dp1, err}
	return e.mock
}

// Convert implements internal.converter
func (mmConvert *ConverterMock) Convert(from string, to string) (dp1 *decimal.Decimal, err error) {
	mm_atomic.AddUint64(&mmConvert.beforeConvertCounter, 1)
	defer mm_atomic.AddUint64(&mmConvert.afterConvertCounter, 1)

	if mmConvert.inspectFuncConvert != nil {
		mmConvert.inspectFuncConvert(from, to)
	}

	mm_params := &ConverterMockConvertParams{from, to}

	// Record call args
	mmConvert.ConvertMock.mutex.Lock()
	mmConvert.ConvertMock.callArgs = append(mmConvert.ConvertMock.callArgs, mm_params)
	mmConvert.ConvertMock.mutex.Unlock()

	for _, e := range mmConvert.ConvertMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.dp1, e.results.err
		}
	}

	if mmConvert.ConvertMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmConvert.ConvertMock.defaultExpectation.Counter, 1)
		mm_want := mmConvert.ConvertMock.defaultExpectation.params
		mm_got := ConverterMockConvertParams{from, to}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmConvert.t.Errorf("ConverterMock.Convert got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmConvert.ConvertMock.defaultExpectation.results
		if mm_results == nil {
			mmConvert.t.Fatal("No results are set for the ConverterMock.Convert")
		}
		return (*mm_results).dp1, (*mm_results).err
	}
	if mmConvert.funcConvert != nil {
		return mmConvert.funcConvert(from, to)
	}
	mmConvert.t.Fatalf("Unexpected call to ConverterMock.Convert. %v %v", from, to)
	return
}

// ConvertAfterCounter returns a count of finished ConverterMock.Convert invocations
func (mmConvert *ConverterMock) ConvertAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmConvert.afterConvertCounter)
}

// ConvertBeforeCounter returns a count of ConverterMock.Convert invocations
func (mmConvert *ConverterMock) ConvertBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmConvert.beforeConvertCounter)
}

// Calls returns a list of arguments used in each call to ConverterMock.Convert.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmConvert *mConverterMockConvert) Calls() []*ConverterMockConvertParams {
	mmConvert.mutex.RLock()

	argCopy := make([]*ConverterMockConvertParams, len(mmConvert.callArgs))
	copy(argCopy, mmConvert.callArgs)

	mmConvert.mutex.RUnlock()

	return argCopy
}

// MinimockConvertDone returns true if the count of the Convert invocations corresponds
// the number of defined expectations
func (m *ConverterMock) MinimockConvertDone() bool {
	for _, e := range m.ConvertMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.ConvertMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterConvertCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcConvert != nil && mm_atomic.LoadUint64(&m.afterConvertCounter) < 1 {
		return false
	}
	return true
}

// MinimockConvertInspect logs each unmet expectation
func (m *ConverterMock) MinimockConvertInspect() {
	for _, e := range m.ConvertMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ConverterMock.Convert with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.ConvertMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterConvertCounter) < 1 {
		if m.ConvertMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to ConverterMock.Convert")
		} else {
			m.t.Errorf("Expected call to ConverterMock.Convert with params: %#v", *m.ConvertMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcConvert != nil && mm_atomic.LoadUint64(&m.afterConvertCounter) < 1 {
		m.t.Error("Expected call to ConverterMock.Convert")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ConverterMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockConvertInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ConverterMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ConverterMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockConvertDone()
}
